spring:
  data:
    mongodb:
      uri: mongodb+srv://freshman:1234@cluster0.dw1q2ck.mongodb.net/?retryWrites=true&w=majority
      #mongodb+srv://freshman:1234@cluster0.dw1q2ck.mongodb.net/?retryWrites=true&w=majority
      database: allba
debug: true
logging:
  level:
    org:
      springframework:
        context: DEBUG
        boot:
          autoconfigure: ERROR
server:
  port: 9090
